name: Docker Image CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file /Presentation/Presentation.WebApi/Dockerfile --tag parstat.azurecr.io/structural-metadata:dev
    - name: Push docker image
      uses: julioarruda/pushimagetoregistry@v1
      with: 
        acr-tokenname: parstat
        acr-token: ${{ secrets.REGISTRY_PASSWORD }}
        acr-account: parstat.azurecr.io
        acr-imagename: parstat.azurecr.io/structural-metadata:dev
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.parstat_key }}
        name: id_rsa # optional
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: stack deploy
      run: ssh parstat@iais.francecentral.cloudapp.azure.com 'cd iais && docker stack deploy --compose-file docker-compose.yml --with-registry-auth iais'
