name: Docker Image CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
env:
  REGISTRY_NAME: parstat
  APP_NAME: structural-metadata

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${ env.REGISTRY_NAME }.azurecr.io
        username: parstat
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Build the Docker image
      run: docker build structural-metadata/Parstat.StrucuralMetadata/Presentation/Presentation.WebApi/ --tag ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
    - name: Push Image to Docker
      run: docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
